classDiagram
    class ResourceManager{
        +LoadMesh()
        +LoadTexture()
        +GetResource()
    }
    class IResourceFactory{
        +CreateMesh()
        +CreateTexture()
    }
    class GLResourceFactory
    class VulkanResourceFactory
    ResourceManager --> IResourceFactory
    IResourceFactory <|-- GLResourceFactory
    IResourceFactory <|-- VulkanResourceFactory
