classDiagram
    class ResourceManager{
        +LoadMesh() ResourceHandle
        +LoadTexture() ResourceHandle
        +GetResource() ResourceHandle
    }
    class IResourceFactory{
        +CreateMesh()
        +CreateTexture()
    }
    class GLResourceFactory
    class VulkanResourceFactory
    class ResourceHandle{
        -UID
        +GetID()
    }

    ResourceManager --> IResourceFactory
    IResourceFactory <|-- GLResourceFactory
    IResourceFactory <|-- VulkanResourceFactory
    ResourceManager --> ResourceHandle

