graph LR
    SceneManager --> Node
    Node --> TransformComponent
    Node --> LightComponent
    Node --> ParticleSystemComponent
    Node --> Renderer
    Renderer --> GLRenderer
    Renderer --> VulkanRenderer
    GLRenderer --> ResourceManager
    VulkanRenderer --> ResourceManager
    ResourceManager --> IMesh
    ResourceManager --> ITexture
