graph LR
    Scene --> Node
    Node --> TransformComponent
    Node --> LightComponent
    Node --> ParticleSystemComponent
    Node --> RendererSystemComponent
    Renderer --> Scene
    Renderer --> GLRenderer
    Renderer --> VulkanRenderer
    GLRenderer --> ResourceManager
    VulkanRenderer --> ResourceManager
    ResourceManager --> IMesh
    ResourceManager --> IMaterial
    IMaterial --> ITexture
